# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions


name: youth_read_feng

on:
  workflow_dispatch:
  schedule:
     - cron: '35 6,9,12 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YOUTH_READ_FENG_1: ${{ secrets.YOUTH_READ_FENG_1 }}
        YOUTH_READ_FENG_2: ${{ secrets.YOUTH_READ_FENG_2 }}
        YOUTH_READ_FENG_3: ${{ secrets.YOUTH_READ_FENG_3 }}
        YOUTH_READ_FENG_4: ${{ secrets.YOUTH_READ_FENG_4 }}
        TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【youth_read_feng_1】'
        if: env.YOUTH_READ_FENG_1
        run: |
          node Task/Youth/youth_read_feng.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_FENG_1 }} 
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          
      - name: '运行 【youth_read_feng_2】'
        if: env.YOUTH_READ_FENG_2
        run: |
          node Task/Youth/youth_read_feng.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_FENG_2 }} 
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          
      - name: '运行 【youth_read_feng_3】'
        if: env.YOUTH_READ_FENG_3
        run: |
          node Task/Youth/youth_read_feng.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_FENG_3 }} 
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          
      - name: '运行 【youth_read_feng_4】'
        if: env.YOUTH_READ_FENG_4
        run: |
          node Task/Youth/youth_read_feng.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_FENG_4 }} 
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
